import type { Fixture } from "@idoa/core";

export const doctorFixtures: Fixture[] = [
  {
    id: "invalid-function",
    title: "Invalid function format",
    description: "Function string does not match Aptos entry function format.",
    kind: "transaction-payload",
    expectedStatus: "fail",
    profile: "strict",
    mode: "offline",
    input: {
      type: "entry_function_payload",
      function: "aptos_account::transfer",
      type_arguments: [],
      arguments: ["0x2", "10"],
      max_gas_amount: 1000,
      gas_unit_price: 1,
      network: "testnet",
    },
  },
  {
    id: "invalid-gas",
    title: "Invalid gas configuration",
    description: "Zero gas unit price should fail.",
    kind: "transaction-payload",
    expectedStatus: "fail",
    profile: "strict",
    mode: "offline",
    input: {
      type: "entry_function_payload",
      function: "0x1::aptos_account::transfer",
      type_arguments: [],
      arguments: ["0x2", "10"],
      max_gas_amount: 30000,
      gas_unit_price: 0,
      network: "testnet",
    },
  },
  {
    id: "invalid-missing-type",
    title: "Invalid missing type",
    description: "Payload misses required type field.",
    kind: "transaction-payload",
    expectedStatus: "fail",
    profile: "strict",
    mode: "offline",
    input: {
      function: "0x1::aptos_account::transfer",
      type_arguments: [],
      arguments: ["0x2", "10"],
      max_gas_amount: 1000,
      gas_unit_price: 1,
      network: "testnet",
    },
  },
  {
    id: "invalid-network",
    title: "Invalid network configuration",
    description: "Network preset is not supported.",
    kind: "network-config",
    expectedStatus: "fail",
    profile: "strict",
    mode: "offline",
    input: {
      type: "entry_function_payload",
      function: "0x1::aptos_account::transfer",
      type_arguments: [],
      arguments: ["0x2", "10"],
      max_gas_amount: 1000,
      gas_unit_price: 1,
      network: "devnet",
    },
  },
  {
    id: "invalid-null-arg",
    title: "Invalid null argument",
    description: "Entry function contains a null argument.",
    kind: "transaction-payload",
    expectedStatus: "fail",
    profile: "strict",
    mode: "offline",
    input: {
      type: "entry_function_payload",
      function: "0x1::aptos_account::transfer",
      type_arguments: [],
      arguments: ["0x2", null],
      max_gas_amount: 1000,
      gas_unit_price: 1,
      network: "testnet",
    },
  },
  {
    id: "valid-eventful",
    title: "Valid payload with events",
    description: "Transaction payload with event sample.",
    kind: "transaction-payload",
    expectedStatus: "pass",
    profile: "relaxed",
    mode: "offline",
    input: {
      type: "entry_function_payload",
      function: "0x1::coin::transfer",
      type_arguments: ["0x1::aptos_coin::AptosCoin"],
      arguments: ["0x9", "77"],
      max_gas_amount: 700,
      gas_unit_price: 1,
      network: "testnet",
      url: "https://api.testnet.aptoslabs.com/v1",
      events: [
        {
          guid: "0x99",
          sequence_number: "1",
          data: {
            receiver: "0x9",
          },
        },
      ],
    },
  },
  {
    id: "valid-generic",
    title: "Valid generic payload",
    description: "Generic JSON validated through shared rules.",
    kind: "generic-json",
    expectedStatus: "pass",
    profile: "relaxed",
    mode: "offline",
    input: {
      type: "entry_function_payload",
      function: "0x1::object::transfer",
      type_arguments: [],
      arguments: ["0xbeef", "0xcafe"],
      max_gas_amount: 750,
      gas_unit_price: 1,
      network: "testnet",
      url: "https://api.testnet.aptoslabs.com/v1",
      events: [],
    },
  },
  {
    id: "valid-local",
    title: "Valid local payload",
    description: "Sample local network payload.",
    kind: "transaction-payload",
    expectedStatus: "pass",
    profile: "relaxed",
    mode: "offline",
    input: {
      type: "entry_function_payload",
      function: "0x1::managed_coin::register",
      type_arguments: ["0x1::aptos_coin::AptosCoin"],
      arguments: [],
      max_gas_amount: 800,
      gas_unit_price: 1,
      network: "local",
      url: "http://127.0.0.1:8080/v1",
      events: [],
    },
  },
  {
    id: "valid-online-simulate",
    title: "Valid online simulation fixture",
    description:
      "Exercises the online simulation path when Aptos RPC is configured.",
    kind: "transaction-payload",
    expectedStatus: "pass",
    profile: "relaxed",
    mode: "online",
    metadata: {
      rpcUrlEnv: "APTOS_RPC_URL",
      simulationRequest: {
        sender: "0x1",
        sequence_number: "0",
        max_gas_amount: "1000",
        gas_unit_price: "1",
        expiration_timestamp_secs: "9999999999",
      },
    },
    input: {
      type: "entry_function_payload",
      function: "0x1::aptos_account::transfer",
      type_arguments: [],
      arguments: ["0x2", "1000"],
      max_gas_amount: 1000,
      gas_unit_price: 1,
      network: "testnet",
      url: "https://api.testnet.aptoslabs.com/v1",
      events: [],
    },
  },
  {
    id: "valid-stake",
    title: "Valid staking payload",
    description: "Sample staking entry function call.",
    kind: "transaction-payload",
    expectedStatus: "pass",
    profile: "relaxed",
    mode: "offline",
    input: {
      type: "entry_function_payload",
      function: "0x1::delegation_pool::add_stake",
      type_arguments: [],
      arguments: ["0x3", "5000"],
      max_gas_amount: 900,
      gas_unit_price: 1,
      network: "mainnet",
      url: "https://api.mainnet.aptoslabs.com/v1",
      events: [],
    },
  },
  {
    id: "valid-transfer",
    title: "Valid transfer payload",
    description: "Basic Aptos coin transfer payload.",
    kind: "transaction-payload",
    expectedStatus: "pass",
    profile: "relaxed",
    mode: "offline",
    input: {
      type: "entry_function_payload",
      function: "0x1::aptos_account::transfer",
      type_arguments: [],
      arguments: ["0x2", "1000"],
      max_gas_amount: 1000,
      gas_unit_price: 1,
      network: "testnet",
      url: "https://api.testnet.aptoslabs.com/v1",
      events: [
        {
          guid: "0x1",
          sequence_number: "0",
          data: {
            amount: "1000",
          },
        },
      ],
    },
  },
];
